import { Prisma, PrismaClient, QuestionTaxonomy, PostType, QuestionStatus } from "@prisma/client";
import { config } from "dotenv";
config({ path: ".env.local" });

const prisma = new PrismaClient({
  datasources: {
    db: { url: process.env.DIRECT_DATABASE_URL ?? process.env.DATABASE_URL },
  },
});

type SeedQ = {
  questionText: string;
  category: QuestionTaxonomy;
  subcategory?: string;
  answerType: PostType;
  options: string[];
  targetAgeGroup?: string;
  targetCity?: string;
  targetRegion?: string;
  targetCountry?: string;
  sourceType?: string;
  aiGenerated?: boolean;
  shareabilityScore?: number;
  sensitivityLevel?: string;
  engagementScore?: number;
};

const Q: SeedQ[] = [
  // OPINION x6
  {
    questionText: "₹1 crore today OR ₹10 lakh every year for 20 years?",
    category: "OPINION",
    subcategory: "Money Mindset",
    answerType: "A_VS_B",
    options: ["₹1 crore today", "₹10 lakh × 20 years"],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "CLASSIC_HOT_TAKE",
    shareabilityScore: 92,
    sensitivityLevel: "LOW",
    engagementScore: 0.95,
  },
  {
    questionText: "Is working from home better than working from office?",
    category: "OPINION",
    subcategory: "Work Culture",
    answerType: "YES_NO",
    options: ["✅ Yes — WFH is better", "❌ No — Office is better"],
    targetAgeGroup: "22-40",
    targetCountry: "India",
    sourceType: "CLASSIC_HOT_TAKE",
    shareabilityScore: 88,
    engagementScore: 0.9,
  },
  {
    questionText: "What's more important in a job?",
    category: "OPINION",
    subcategory: "Work Values",
    answerType: "A_VS_B",
    options: ["💰 More Money", "⚖️  Better Work-Life Balance"],
    targetAgeGroup: "22-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.93,
    shareabilityScore: 85,
  },
  {
    questionText: "Would you move to another city for a 30% salary increase?",
    category: "OPINION",
    subcategory: "Relocation",
    answerType: "YES_NO",
    options: ["✅ Yes, I'd move", "❌ No — family/friends/city matter more"],
    targetAgeGroup: "22-32",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.86,
    shareabilityScore: 80,
  },
  {
    questionText: "Overall — is AI making life better?",
    category: "OPINION",
    subcategory: "AI Sentiment",
    answerType: "DECISION",
    options: ["✅ Yes, better", "🤷 Neutral so far", "❌ No, making things worse"],
    targetAgeGroup: "18-40",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.88,
    shareabilityScore: 82,
  },
  {
    questionText: "Rate the impact of social media on your generation (1–10):",
    category: "OPINION",
    subcategory: "Social Impact",
    answerType: "RATING",
    options: ["1 (terrible)", "2", "3", "4", "5", "6", "7", "8", "9", "10 (excellent)"],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.8,
    sensitivityLevel: "LOW",
  },
  // LIFESTYLE x6
  {
    questionText: "Pizza 🍕 vs Burger 🍔?",
    category: "LIFESTYLE",
    subcategory: "Food",
    answerType: "A_VS_B",
    options: ["🍕 Pizza", "🍔 Burger"],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    shareabilityScore: 90,
    engagementScore: 0.96,
  },
  {
    questionText: "Tea ☕ vs Coffee ☕?",
    category: "LIFESTYLE",
    subcategory: "Beverage",
    answerType: "A_VS_B",
    options: ["☕ Chai / Tea", "☕ Coffee"],
    targetAgeGroup: "16-45",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.9,
    shareabilityScore: 86,
  },
  {
    questionText: "Mountains 🏔️ vs Beach 🏖️?",
    category: "LIFESTYLE",
    subcategory: "Travel vibe",
    answerType: "A_VS_B",
    options: ["🏔️ Mountains", "🏖️ Beach"],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.9,
    shareabilityScore: 89,
  },
  {
    questionText: "Morning person ☀️ or Night owl 🌙?",
    category: "LIFESTYLE",
    subcategory: "Sleep schedule",
    answerType: "A_VS_B",
    options: ["☀️ Early bird / Morning person", "🌙 Night owl"],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.89,
    shareabilityScore: 82,
  },
  {
    questionText: "Would you rather travel the world for a year OR buy a brand new ₹25 lakh car?",
    category: "LIFESTYLE",
    subcategory: "Experiences vs Things",
    answerType: "A_VS_B",
    options: ["✈️  One year world travel", "🚗 Brand new ₹25 lakh car"],
    targetAgeGroup: "22-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    shareabilityScore: 91,
    engagementScore: 0.93,
  },
  {
    questionText: "Which best describes your ideal Sunday?",
    category: "LIFESTYLE",
    subcategory: "Chill",
    answerType: "POLL",
    options: [
      "🎉 Out with friends / party",
      "🎮 Gaming / series marathon",
      "👨‍👩‍👧‍👦 Quality family time",
      "😴 Sleep + lazy read",
      "🏃 Hike / long drive / outdoors",
    ],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.85,
  },
  // PERSONALITY x6
  {
    questionText: "When making a MAJOR life decision — what do you rely on most?",
    category: "PERSONALITY",
    subcategory: "Decision Style",
    answerType: "MULTIPLE_CHOICE",
    options: ["🧠 Pure Logic / Pro-Con list", "❤️ Gut / Emotion", "👥 Ask trusted people / Advice", "✨ Intuition / Instinct"],
    targetAgeGroup: "18-40",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.91,
    shareabilityScore: 88,
  },
  {
    questionText: "A friend texts 'I need help' at 2am. Your move?",
    category: "PERSONALITY",
    subcategory: "Loyalty",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🚗 Leave right now — I'm there in 30 min",
      "📞 Call them immediately",
      "💬 Text back: what happened?",
      "💤 Next morning check — 2am can wait",
    ],
    targetAgeGroup: "18-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.87,
  },
  {
    questionText: "Your friend just posted something you disagree with publicly. You:",
    category: "PERSONALITY",
    subcategory: "Conflict Style",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🗣️ Comment my counter opinion publicly",
      "💬 DM them privately",
      "🤫 Scroll past silently",
      "😤 Unfollow / mute",
    ],
    targetAgeGroup: "18-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.86,
  },
  {
    questionText: "Pick ONE superpower you'd actually use every day?",
    category: "PERSONALITY",
    subcategory: "Fantasy",
    answerType: "MULTIPLE_CHOICE",
    options: ["⏰ Stop / rewind time", "🩹 Heal anyone", "🧠 Read minds", "🚶 Teleport anywhere", "🕵️ Be invisible"],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.94,
    shareabilityScore: 92,
  },
  {
    questionText: "Your phone dies 1% — no charger for 6 hours. Your reaction?",
    category: "PERSONALITY",
    subcategory: "Digital detox",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "😱 PANIC — find a charger ASAP",
      "😐 Mildly annoyed",
      "😌 Relax — good digital detox",
      "🎉 Best thing all day",
    ],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.88,
  },
  {
    questionText: "Scale 1–10 — how much do you care what 'people on the internet' think of you?",
    category: "PERSONALITY",
    subcategory: "Validation seeking",
    answerType: "RATING",
    options: ["1 (zero cares)", "2", "3", "4", "5", "6", "7", "8", "9", "10 (deeply care)"],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.82,
  },
  // MONEY x4
  {
    questionText: "₹50,000 right now OR ₹75,000 guaranteed one year later?",
    category: "MONEY",
    subcategory: "Discounting",
    answerType: "A_VS_B",
    options: ["💸 ₹50,000 — cash now", "⏳ ₹75,000 — one year later"],
    targetAgeGroup: "20-40",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    shareabilityScore: 83,
    engagementScore: 0.9,
  },
  {
    questionText: "Best first thing to do with your first salary ₹30,000?",
    category: "MONEY",
    subcategory: "Money priorities",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🏦 Emergency fund / savings (6 months)",
      "📈 Invest in MF / stock / FD",
      "🎁 Family gifts + treat self small",
      "🛒 Buy that thing you always wanted",
    ],
    targetAgeGroup: "22-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.91,
    shareabilityScore: 85,
  },
  {
    questionText: "Would you take a ₹20,000 personal loan for a 10-day international trip?",
    category: "MONEY",
    subcategory: "Debt tolerance",
    answerType: "YES_NO",
    options: ["✅ Yes — YOLO", "❌ No — save first"],
    targetAgeGroup: "22-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.87,
  },
  {
    questionText: "Guess the price of this watch ⌚ (Seiko, sapphire glass, solar powered, titanium):",
    category: "MONEY",
    subcategory: "Price Guess",
    answerType: "PRICE",
    options: ["Below ₹15,000", "₹15,000 – ₹25,000", "₹25,000 – ₹45,000", "₹45,000 – ₹80,000", "₹80,000+"],
    targetAgeGroup: "22-45",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.83,
  },
  // CAREER x4
  {
    questionText: "10-year goal: Job vs Business?",
    category: "CAREER",
    subcategory: "Path Choice",
    answerType: "A_VS_B",
    options: ["💼 Stable high-salary Job", "🚀 Startup / Business"],
    targetAgeGroup: "20-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    shareabilityScore: 89,
    engagementScore: 0.92,
  },
  {
    questionText: "Would you accept a 20% pay cut in exchange for a 4-day work week?",
    category: "CAREER",
    subcategory: "Work hours tradeoff",
    answerType: "YES_NO",
    options: ["✅ Yes — love 3-day weekends", "❌ No — need the 20%"],
    targetAgeGroup: "22-40",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.94,
    shareabilityScore: 91,
  },
  {
    questionText: "30% higher offer from a company 90-min away (current is walkable). Take it?",
    category: "CAREER",
    subcategory: "Commute trade",
    answerType: "DECISION",
    options: ["✅ Take higher pay", "🤔 Negotiate hybrid 2-3 days WFH", "❌ Stay — commute kills QoL"],
    targetAgeGroup: "24-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.88,
  },
  {
    questionText: "After 10 years in same career — switch to new field?",
    category: "CAREER",
    subcategory: "Pivot",
    answerType: "YES_NO",
    options: ["✅ Yes — always learning", "❌ Too risky — double down"],
    targetAgeGroup: "30-45",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.82,
  },
  // RELATIONSHIP x4
  {
    questionText: "MOST important in a long-term partner?",
    category: "RELATIONSHIP",
    subcategory: "Values",
    answerType: "MULTIPLE_CHOICE",
    options: ["🔒 Trust", "💬 Communication", "🫶 Shared values", "🎉 Fun + laughter"],
    targetAgeGroup: "20-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.9,
    sensitivityLevel: "LOW",
  },
  {
    questionText: "How soon is 'too soon' to say I love you?",
    category: "RELATIONSHIP",
    subcategory: "Timeline",
    answerType: "MULTIPLE_CHOICE",
    options: ["<1 month → too soon", "2–3 months", "4–6 months", "Whenever you feel it"],
    targetAgeGroup: "18-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.9,
    shareabilityScore: 87,
  },
  {
    questionText: "Should you share phone passwords with your partner?",
    category: "RELATIONSHIP",
    subcategory: "Boundaries",
    answerType: "YES_NO",
    options: ["✅ Yes — nothing to hide", "❌ No — boundaries healthy"],
    targetAgeGroup: "18-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.87,
  },
  {
    questionText: "Partner wants to move cities for THEIR dream job (2hrs flight away). You?",
    category: "RELATIONSHIP",
    subcategory: "Long distance",
    answerType: "DECISION",
    options: ["🥹 Move with them / make it work", "📞 Try long distance", "👋 Break up — geography wins"],
    targetAgeGroup: "22-32",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.86,
    sensitivityLevel: "MEDIUM",
  },
  // TECHNOLOGY x4
  {
    questionText: "iPhone 📱 vs Android 🤖?",
    category: "TECHNOLOGY",
    subcategory: "Phone OS",
    answerType: "A_VS_B",
    options: ["📱 iPhone", "🤖 Android"],
    targetAgeGroup: "16-40",
    targetCountry: "India",
    sourceType: "CLASSIC_HOT_TAKE",
    engagementScore: 0.96,
    shareabilityScore: 94,
  },
  {
    questionText: "Which AI tool do you actually use weekly?",
    category: "TECHNOLOGY",
    subcategory: "AI Adoption",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "💬 ChatGPT / Gemini",
      "🎨 Midjourney / image AI",
      "🧑‍💻 GitHub Copilot / code AI",
      "None / not really using AI tools yet",
    ],
    targetAgeGroup: "18-40",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.89,
  },
  {
    questionText: "₹2,000/month for a really good AI assistant subscription — worth it?",
    category: "TECHNOLOGY",
    subcategory: "Willingness to pay",
    answerType: "YES_NO",
    options: ["✅ Worth every rupee", "❌ Free tools are enough"],
    targetAgeGroup: "20-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.83,
  },
  {
    questionText: "In 2026 — is a laptop still necessary? (You already own a powerful phone + tablet)",
    category: "TECHNOLOGY",
    subcategory: "Form factor",
    answerType: "YES_NO",
    options: ["✅ Laptop still needed", "❌ Phone + tablet enough"],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.84,
  },
  // SOCIAL_MEDIA x3
  {
    questionText: "100K Instagram followers vs 10 real-life close friends?",
    category: "SOCIAL_MEDIA",
    subcategory: "Fame vs depth",
    answerType: "A_VS_B",
    options: ["👥 10 close friends", "📱 100K followers"],
    targetAgeGroup: "16-28",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.93,
    shareabilityScore: 90,
  },
  {
    questionText: "If you could KEEP ONLY ONE social app, which one stays?",
    category: "SOCIAL_MEDIA",
    subcategory: "App loyalty",
    answerType: "MULTIPLE_CHOICE",
    options: ["📸 Instagram", "🎥 YouTube / Shorts", "🐦 X / Twitter", "💬 WhatsApp", "🎮 Reddit / Discord"],
    targetAgeGroup: "16-28",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.92,
    shareabilityScore: 88,
  },
  {
    questionText: "30-day NO social media challenge — could you do it?",
    category: "SOCIAL_MEDIA",
    subcategory: "Digital detox",
    answerType: "YES_NO",
    options: ["✅ Easy", "❌ I'd fail within a week"],
    targetAgeGroup: "16-28",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.85,
  },
  // ENTERTAINMENT x3
  {
    questionText: "Movie night in theatre vs game night at home?",
    category: "ENTERTAINMENT",
    subcategory: "Evening plan",
    answerType: "A_VS_B",
    options: ["🎬 Movie night", "🎮 Game night"],
    targetAgeGroup: "16-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.86,
  },
  {
    questionText: "Which should we pick this weekend?",
    category: "ENTERTAINMENT",
    subcategory: "Content picker",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🎬 New release in theatre",
      "📺 Season finale streaming marathon",
      "🎧 Music gig / concert",
      "🎲 Board / video game night",
      "🏟️  Live sports match",
    ],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.86,
  },
  {
    questionText: "Rate Indian cinema 1–10:",
    category: "ENTERTAINMENT",
    subcategory: "Bollywood love",
    answerType: "RATING",
    options: ["1 – skip", "2", "3", "4", "5", "6", "7", "8", "9", "10 – obsessed"],
    targetAgeGroup: "16-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.83,
  },
  // FOOD x3
  {
    questionText: "₹500 budget dinner tonight — pick:",
    category: "FOOD",
    subcategory: "Weeknight dinner",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🍕 Pizza / Italian",
      "🍔 Burger + fries combo",
      "🍜 Chinese / Asian / noodles",
      "🍱 Local place — proper thali/meal",
      "🥗 Healthy + juice / salad bar",
    ],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.89,
  },
  {
    questionText: "Best Indian breakfast? ₹400 budget for two:",
    category: "FOOD",
    subcategory: "Breakfast",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🥞 South Indian (idli / dosa / vada)",
      "🫓 North Indian (paratha / chole bhature)",
      "🥪 Sandwich + eggs / toast",
      "🍲 Poha + poori bhaji / snack",
    ],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.88,
  },
  {
    questionText: "Date night: home cooked vs fancy restaurant out?",
    category: "FOOD",
    subcategory: "Date night",
    answerType: "A_VS_B",
    options: ["🏠 Home cooked impress", "🍽️ Out for restaurant"],
    targetAgeGroup: "20-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.84,
  },
  // TRAVEL x3
  {
    questionText: "5-day trip ₹25k budget — where to?",
    category: "TRAVEL",
    subcategory: "Domestic pick",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🏔️ Himachal / Uttarakhand hills",
      "🏖️ Goa / Kerala beaches",
      "🏙️ Mumbai or Delhi city explore",
      "🛖 Slow home stay / local",
    ],
    targetAgeGroup: "20-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.89,
    shareabilityScore: 84,
  },
  {
    questionText: "Same budget: Goa 🏖️ or Bali 🌴 bachelor/ette trip?",
    category: "TRAVEL",
    subcategory: "Beach trip",
    answerType: "A_VS_B",
    options: ["🏖️ Goa", "🌴 Bali"],
    targetAgeGroup: "22-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.9,
    shareabilityScore: 89,
  },
  {
    questionText: "Your travel style?",
    category: "TRAVEL",
    subcategory: "Style",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🗺️ Every hour itenerary planned",
      "🎒 Backpack spontaneous flow",
      "🏨 Resort all-inclusive relax",
      "🚶 Road trip self drive",
    ],
    targetAgeGroup: "20-35",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.87,
  },
  // LOCAL_CITY x6
  {
    questionText: "Mumbai — 1.5hrs away — weekend getaway pick:",
    category: "LOCAL_CITY",
    subcategory: "Mumbai getaway",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🏖️ Alibaug / Kashid beach",
      "🏔️ Lonavala / Khandala ghats",
      "🎭 SoBo + café + art gallery + dinner",
      "😴 Stay home and rest",
    ],
    targetAgeGroup: "18-35",
    targetCity: "Mumbai",
    targetRegion: "Maharashtra",
    targetCountry: "India",
    sourceType: "LOCAL_SEEDED",
    engagementScore: 0.9,
  },
  {
    questionText: "Mumbai commute — which is WORSE at 9am peak hour?",
    category: "LOCAL_CITY",
    subcategory: "Mumbai commute",
    answerType: "A_VS_B",
    options: ["🚆 Local train", "🚍 BEST bus"],
    targetAgeGroup: "18-40",
    targetCity: "Mumbai",
    targetRegion: "Maharashtra",
    targetCountry: "India",
    sourceType: "LOCAL_SEEDED",
    engagementScore: 0.92,
    shareabilityScore: 90,
  },
  {
    questionText: "Pune weekend — where you headed?",
    category: "LOCAL_CITY",
    subcategory: "Pune getaway",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🏕️ Lonavala picnic point",
      "☕ KP / Koregaon café hopping",
      "🎥 Movie + mall",
      "🏡 Stay home",
    ],
    targetAgeGroup: "18-35",
    targetCity: "Pune",
    targetRegion: "Maharashtra",
    targetCountry: "India",
    sourceType: "LOCAL_SEEDED",
    engagementScore: 0.86,
  },
  {
    questionText: "Bangalore traffic: ORR stretch vs HSR/Silk Board — which is WORSE?",
    category: "LOCAL_CITY",
    subcategory: "Bangalore traffic",
    answerType: "A_VS_B",
    options: ["🛣️ ORR stretch", "📍 HSR / Silk Board"],
    targetAgeGroup: "22-35",
    targetCity: "Bangalore",
    targetRegion: "Karnataka",
    targetCountry: "India",
    sourceType: "LOCAL_SEEDED",
    engagementScore: 0.9,
    shareabilityScore: 88,
  },
  {
    questionText: "Bangalore 1BHK ₹25k rent — where would you live?",
    category: "LOCAL_CITY",
    subcategory: "Bangalore rental",
    answerType: "MULTIPLE_CHOICE",
    options: ["📍 HSR Layout", "📍 Indiranagar", "📍 Whitefield", "📍 Marathahalli"],
    targetAgeGroup: "22-32",
    targetCity: "Bangalore",
    targetRegion: "Karnataka",
    targetCountry: "India",
    sourceType: "LOCAL_SEEDED",
    engagementScore: 0.88,
  },
  {
    questionText: "Delhi November evening out on a date — pick:",
    category: "LOCAL_CITY",
    subcategory: "Delhi winter",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "🍗 Paranthe wali gali / Old Delhi",
      "🪔 Connaught Place walk + coffee",
      "🏙️ Hauz Khas village cafes",
      "🚙 Night drive India Gate",
    ],
    targetAgeGroup: "18-35",
    targetCity: "Delhi",
    targetRegion: "Delhi NCR",
    targetCountry: "India",
    sourceType: "LOCAL_SEEDED",
    engagementScore: 0.89,
  },
  // INTERNET_TREND x3
  {
    questionText: "PREDICTION: India will win 2027 ICC Men's Cricket World Cup?",
    category: "INTERNET_TREND",
    subcategory: "Cricket hot",
    answerType: "PREDICTION",
    options: ["🏆 YES WIN IT", "❌ NO"],
    targetAgeGroup: "16-40",
    targetCountry: "India",
    sourceType: "MANUAL_TREND",
    engagementScore: 0.96,
    shareabilityScore: 97,
  },
  {
    questionText: "Short-form Reel/TikTok dance trends — do you actually watch them?",
    category: "INTERNET_TREND",
    subcategory: "Short video habit",
    answerType: "MULTIPLE_CHOICE",
    options: [
      "✅ Yes, daily — addicted",
      "Sometimes — swipe through",
      "I make / post my own",
      "❌ Don't watch — skip",
    ],
    targetAgeGroup: "16-30",
    targetCountry: "India",
    sourceType: "MANUAL_SEEDED",
    engagementScore: 0.85,
  },
  {
    questionText: "AI image generation as a career in 2026 — rate 1–10:",
    category: "INTERNET_TREND",
    subcategory: "AI hype",
    answerType: "RATING",
    options: ["1 dead", "2", "3", "4", "5", "6", "7", "8", "9", "10 hottest career"],
    targetAgeGroup: "18-35",
    targetCountry: "India",
    sourceType: "TREND_GEN_SCAFFOLD",
    engagementScore: 0.8,
  },
];

async function main() {
  console.log(`Seeding up to ${Q.length} assessment questions…`);
  let created = 0;
  let skipped = 0;
  for (const q of Q) {
    const exists = await prisma.assessmentQuestion.count({
      where: { questionText: q.questionText, category: q.category },
    });
    if (exists > 0) {
      skipped++;
      continue;
    }
    const createdQ = await prisma.assessmentQuestion.create({
      data: {
        questionText: q.questionText,
        category: q.category,
        subcategory: q.subcategory ?? null,
        answerType: q.answerType,
        targetAgeGroup: q.targetAgeGroup ?? null,
        targetCity: q.targetCity ?? null,
        targetRegion: q.targetRegion ?? null,
        targetCountry: q.targetCountry ?? "India",
        sourceType: q.sourceType ?? "MANUAL_SEEDED",
        aiGenerated: q.aiGenerated ?? false,
        shareabilityScore: q.shareabilityScore ?? null,
        sensitivityLevel: q.sensitivityLevel ?? null,
        status: QuestionStatus.PUBLISHED,
        approvedAt: new Date(),
        publishedAt: new Date(),
        timesSelected: 0,
        voteCount: 0,
        minSampleSize: 50,
        engagementScore: q.engagementScore != null ? new Prisma.Decimal(String(q.engagementScore)) : null,
        options: {
          create: q.options.map((label, i) => ({
            sortOrder: i + 1,
            label,
          })),
        },
      },
    });
    created++;
    console.log(
      `  + [${createdQ.id.slice(0, 8)}…] ${String(q.category).padEnd(14)} ${String(q.answerType).padEnd(16)} → ${q.questionText.slice(0, 62)}…`
    );
  }
  const total = await prisma.assessmentQuestion.count();
  console.log(`\n✅ Done. Created ${created} new, skipped ${skipped} existing. Total questions in DB: ${total}`);
  const cat = await prisma.assessmentQuestion.groupBy({
    by: ["category"],
    _count: { _all: true },
  });
  console.table(
    cat.map((r) => ({
      category: r.category,
      count: r._count._all,
    }))
  );
  console.log("\n✅ Answer types distribution:");
  const at = await prisma.assessmentQuestion.groupBy({
    by: ["answerType"],
    _count: { _all: true },
  });
  console.table(
    at.map((r) => ({
      answerType: r.answerType,
      count: r._count._all,
    }))
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => prisma.$disconnect());
