export const WHATDO_FUNNEL_EVENT_NAMES = [
  "WHATDO_LANDING_VIEWED",
  "QUIZ_STARTED",
  "QUESTION_SHOWN",
  "ANSWER_SUBMITTED",
  "RESULT_VIEWED",
  "RESULT_REVEALED",
  "SHARE_CARD_DOWNLOADED",
  "SHARE_BUTTON_CLICKED",
  "SHARE_LINK_CLICKED",
  "SHARE_LINK_SIGNUP",
  "REFERRAL_SHARED",
  "REFERRAL_COMPLETED",
  "FRIEND_CHALLENGED",
  "AI_PROMPT_COPIED",
] as const;

export type WhatDoFunnelEventName = (typeof WHATDO_FUNNEL_EVENT_NAMES)[number];
